name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run : ls -lart .github/workflows/
    - uses: SonarQubeCoverageJava/.github/workflows/maven-reusable.yml@master
